### ISSUE TITLE
Please clarify copyright

### ISSUE THREAD

**Issue by markxnelson** [chaostoolkit-incubator/chaostoolkit-oci#10]
Hi, 
I am interested in using and contributing to this project.  Would you be able to clarify who owns the copyright?  I don't see any notices in the repo.  
Thanks a lot for your help,
Mark Nelson

**Comment by Lawouach** [comment]
Hi @markxnelson,

My take is that the code is owned by the Chaos Toolkit team once it integrates the incubator. What would be your take @nazarenof?

**Comment by markxnelson** [comment]
Hi @Lawouach 
We spoke with @nazarenof offline - he no longer has a github account, so cannot answer.  He said he agreed with your statement. 
What is the process to contribute?  Would you give us the ability to merge/commit to this repo itself, or would submit PR's from a fork to someone (you?) to review and merge?  
If we said that we were willing to "own" this one repo and commit to making the oci plugin work and keeping it up to date, does that change anything?
Thanks

**Comment by Lawouach** [comment]
Hi @markxnelson, thanks for clarifying with @nazarenof. I didn't want to make it sound like we'd steal things away. I think we'll need to clarify that bit in our documentation.

Back to your question of contribution. We were thinking of opening up direct access to repositories to speed up/simplify contributions. But we haven't had the chance to document that governance yet.

Usually, we work via PRs from a fork indeed. However, as you offer a solid commitment to give life to this extension, I'm happy to make you a contributor. I will still request that commits are signed so that the DCO can be respected. I assume you'll agree this helps traceability of contributions.

**Comment by markxnelson** [comment]
We would definitely use git signoff on all commits, does that cover it, or is there a contribution agreement to print/sign too?

**Comment by Lawouach** [comment]
DCO only on the CTK projects, lower barrier and good enough considering our Apache license we think.

**Comment by markxnelson** [comment]
Ok sounds good. Could you give me a link to the DCO for reference please?
The github id's are mine and @hyder

**Comment by Lawouach** [comment]
Sure: https://developercertificate.org/

**Comment by markxnelson** [comment]
thanks :) I thought it was something unique to this project :)

**Comment by Lawouach** [comment]
Hah. No pb, it is less heavyweight than a CLA and promotes faster contributions IMO.

**Comment by Lawouach** [comment]
I have invited you to the @chaostoolkit-incubator/oci with write permissions on this repository. Hope this makes a good start.

**Comment by markxnelson** [comment]
great, thanks!
we will take a little while to get up to speed and make sure we can build everything and run the tests and so on, and then we will get to work on the code in earnest

**Comment by markxnelson** [comment]
hi @Lawouach - just an update - we are working on a necessary approval from our side to sign the DCA.  we are working on some code updates & once we get the approvals, we will be able to start adding to this repo.

**Comment by Lawouach** [comment]
This is great news. Looking forward to it. I hope the DCO and license won't be an issue.

**Comment by markxnelson** [comment]
Hi @Lawouach - finally got all of the approvals in place :)  We are going to start working on some contributions now!

**Comment by Lawouach** [comment]
This is great. All good things wait for those who can wait :)

**Comment by Lawouach** [comment]
Hey @markxnelson, it's fantastic you started merging into this repo! Thak you and well done.

**Comment by markxnelson** [comment]
thanks, working on more good stuff to come.  will close this issue for now.  feel free to reopen/etc. if you need anything.
